### ISSUE TITLE
org not in vcard, overwritten by e-mail

### ISSUE THREAD

**Issue by codexsolo** [six-two/qr.html#7]
I'm not entirely sure if it's a bug or if I'm the bug.

When generating a qr the organisation in missing and instead the e-mail is also the organisation name.

<img width="842" alt="Screenshot 2024-10-10 at 10 20 40" src="https://github.com/user-attachments/assets/56acbb59-e013-4ac1-a2a4-b634b5e1a3f4">

**Comment by codexsolo** [comment]
Forgot to mention that I'm scanning with an iPhone (native camera app) with iOS 18. Is the reader the issue?

**Comment by six-two** [comment]
Hi, I'm no expert with the vCard format. But I just scanned your code on my iPhone (iOS 18.0.1) with the camera app and it looks correct. This is what it looks like when I scan it and choose `Create New Contact`:

![image](https://github.com/user-attachments/assets/c1c1707e-0f59-491b-96e7-795ca645144a)

**Comment by codexsolo** [comment]
This is an iOS 18 bug then, i'm currently on 18.0.1.
![Screenshot 2024-10-11 at 14 29 33](https://github.com/user-attachments/assets/12ea2e0f-ad0f-44b9-8f9c-1317d212fc59)
